#spring.main.web-application-type=none
# Puerto del servidor
#server.port=3306

spring.main.web-application-type=servlet
server.port=8081


# ===== DATASOURCE =====
spring.datasource.url=jdbc:mysql://192.168.5.25:3306/ekitop?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SSL/TLS keystore (deshabilitado por ahora)
server.keystore.path=/home/zornotza/Dokumentuak/server_keystore.jks
server.keystore.password=admin1

# Gmail SMTP
mail.smtp.host=smtp.gmail.com
mail.smtp.port=465
mail.smtp.user=ekitop26@gmail.com
mail.smtp.pass=wnfvbckowxvslalk

# FTP
ftp.host=localhost
ftp.port=21
ftp.user=gonbidatua
ftp.pass=gonbidatua
ftp.baseDir=/tickets